[package]
name = "file_encryption_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
cocoon = "0.4.3"
borsh = { version = "1.5.7", features = ["derive"] }
eframe = "0.33.2"
env_logger = "0.11.8"
rfd = "0.15.4"
